apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
    method: fromcode
    another: label
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
  - image: nginx
    name: nginx
